### ISSUE TITLE
Support for AmneziaWG protocol

### ISSUE THREAD

**Issue by clinkme4g** [pufferffish/wireproxy#101]
It's a fork of [WireGuard-Go](https://github.com/WireGuard/wireguard-go) and offers protection against detection by Deep Packet Inspection (DPI) systems, because in some countries standard VPN protocols are totally blocked.
[https://github.com/amnezia-vpn/amneziawg-go](url)

**Comment by pufferffish** [comment]
This will not be done for reasons stated in #102
