### ISSUE TITLE
/etc/localtime open: no such file or directory

### ISSUE THREAD

**Issue by fanite** [pufferffish/wireproxy#110]
2024/04/17 21:42:40 populating ruleset for "/etc/localtime" with access {execute,read_file}: open: no such file or directory

**Comment by pufferffish** [comment]
Which distro are you using and what command did you use to launch wireproxy?

**Comment by fanite** [comment]
> Which distro are you using and what command did you use to launch wireproxy?

Updated issue information

**Comment by jinnatar** [comment]
Facing this as well. It seems the landlock config at https://github.com/pufferffish/wireproxy/blob/a6797166eba8cfd77de54e8ede1051a9bf4baeee/cmd/wireproxy/main.go#L78 assumes that a whole bunch of paths will exist, which in fact do not and should not exist in a container environment.
