### ISSUE TITLE
Default configuration location

### ISSUE THREAD

**Issue by danyer** [pufferffish/wireproxy#119]
Hi,

thank you for wireproxy!

Is it possible to implement a default configuration location? In this way one will be able to call wireproxy without "-c config_file" and use that option only to overwrite the default one. I think ~/.config/wireproxy.conf would be a good location. Of course, to be fully XDG Base Specification compliant:
"If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used."

Thank you for considering this.

**Comment by shaerpour** [comment]
@pufferffish 
Is it ok to work on this and add PR?
We can add default config paths on 
/etc/wireproxy/wireproxy.conf
and
$HOME/.config/wireproxy.conf.
If they does not exist, send error for getting config path option.

**Comment by pufferffish** [comment]
> Is it ok to work on this and add PR?

Feel free to make a PR, I will review and merge it if it's ok
