### ISSUE TITLE
Prefer ipv6 over ipv4 in socks proxy

### ISSUE THREAD

**Issue by FireMasterK** [pufferffish/wireproxy#75]
With a configuration having:
```
[Socks5]
BindAddress = 0.0.0.0:1080
```

When I run `curl --proxy socks5://127.0.0.1:1080 icanhazip.com` I get an ipv4 address, although that hostname is dual stack. I would expect to see an ipv6 address here.
When I run `curl --proxy socks5://127.0.0.1:1080 ipv6.icanhazip.com` I see an ipv6 address.

**Comment by kubrickfr** [comment]
`socks5://` protocol in curl resolves hostnames locally, therefore it's a problem with your local setup (for example, you don't have IPv6 on your machine and the local resolver ignores IPv6 answers from the DNS.

Try using hte `socks5h://` protocol instead. (see `man curl`)
