### ISSUE TITLE
High ram usage

### ISSUE THREAD

**Issue by bart3nder** [pufferffish/wireproxy#80]
Hello, Thanks for the amazing tool! It comes real handy for my development environment.
As I send many requests through my wireproxy socks, It continuously uses ram more and more (for the cache I guess) and I have to reset it by killing the process and restart it. Is there anything you can do about it? It would be great that the tool can handle these things without manual work.
Thanks Again!

**Comment by kubrickfr** [comment]
Wireproxy is using https://github.com/armon/go-socks5 which has not been updated in 7 years, without looking too deeply into it, I suspect this might be the culprit and it should be changed...

**Comment by Manouchehri** [comment]
I noticed this as well, over a couple hours it becomes the highest memory hog.

**Comment by Manouchehri** [comment]
I don't see any mention of `cache` or `caching` in either wireproxy or `go-socks5`. I feel like it's probably a resource leak somewhere.
