### ISSUE TITLE
Reliability Issues Using with 3rd Party VPN

### ISSUE THREAD

**Issue by lendenis** [pufferffish/wireproxy#92]
Hello,

I am trying to use wireproxy over a commercial VPN with wireguard. The wireproxy connection is not reliable, i need to restart it from time to time frequently.

Is there a parameter, like keep alive, so it can reconnect or keep the connection alive?

Thanks

**Comment by kubrickfr** [comment]
Yes, you probably need to reduce the MTU in your wireproxy/wireguard configuration.
Mullvad, for example, reduces your MTU to 1420, meaning that (if you connect wireproxy using IPv4) you can't use more that 1360. But just to be safe you could set it to 1320/1300 and it would insure more compatibility.

**Comment by lendenis** [comment]
After I change the MTU values as 1320 the reliability increased. Thanks for the suggestion.
